version: '3.8'

# volumes:
#   golang:

services:
  docker-golang:
    container_name: docker-golang
    tty: true
    image: golang
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/go
      # - golang:/go/src/app
