FROM php:7.3-fpm

# RUN apt-get update \
#   && apt-get install iputils-ping \
#   && docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt-get update && apt-get install -y --fix-missing \
  apt-utils gnupg \
  curl software-properties-common net-tools wget git-all

# 解決安裝 php-zip 問題
RUN echo "deb http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list
RUN echo "deb-src http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list
RUN curl -sS --insecure https://www.dotdeb.org/dotdeb.gpg | apt-key add -
RUN apt-get install -y zlib1g-dev libzip-dev zip unzip

# 新增 PHP extension
RUN docker-php-ext-install mysqli bcmath zip pdo_mysql

# 安裝 XDebug
RUN pecl install xdebug

# 複製 ini
COPY ./php.ini $PHP_INI_DIR
# COPY ./php-fpm.conf /usr/local/etc/

# Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
  && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
  && php composer-setup.php  --filename=composer --install-dir=/usr/local/bin/ \
  && php -r "unlink('composer-setup.php');"

  # 把 composer 全域包進 path
ENV PATH=$PATH:~/.composer/vendor/bin

# Laravel
# RUN composer global require laravel/installer

# Symfony
RUN wget https://get.symfony.com/cli/installer -O - | bash \
  && mv /root/.symfony/bin/symfony /usr/local/bin/symfony

# Node & NPM
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get -y install nodejs

WORKDIR /usr/src/myapp

# WORKDIR /var/www/html

# 修改 apache 預設目錄
# RUN sed -i -e 's/\/var\/www\/html/\/var\/www\/html\/public/i' /etc/apache2/sites-enabled/000-default.conf

# 按照自編的 route
# RUN a2enmod rewrite
